### ISSUE TITLE
Crash on startup with Screencapper 1.4.3 on Fabric 1.20.1

### ISSUE THREAD

**Issue by Alexander317** [Deftu/Screencapper#10]
https://mclo.gs/4ME4qWQ - Message from Fabric Loader
https://mclo.gs/LaQX7rT - latest log

Loader - Modrinth
Fabric Loader version - 0.15.11
All mods have the latest version available

I've tried to re-install java and to repair the instance, but nothing helped

**Comment by Deftu** [comment]
Resolved in 6daff31da397f9249dd0670ff331bc0833e5a0cf.
