### ISSUE TITLE
Screencapper license in MC and license on MR varies

### ISSUE THREAD

**Issue by TechPro424** [Deftu/Screencapper#8]
As you can see in the image, the license of screencapper in MC is GPLv3.0
However, on MR and GH, it is LGPLv3.0

![image](https://github.com/Deftu/Screencapper/assets/86620085/4c329691-b474-4073-8f0b-815d98a4001a)

**Comment by Deftu** [comment]
Resolved in c39af18c4641134ed6a98d2a5ccde1720a878912.
